### ISSUE TITLE
Regression with 1.3.15: Methods of .NET Objects passed to Lua cannot be called

### ISSUE THREAD

**Issue by Fragtality** [neolithos/neolua#194]
One of my Applications ([Any2GSX](https://github.com/Fragtality/Any2GSX)) uses your great Library. ❤️ (Actually I have two Apps using it, but only one is affected ^^)

In that App, NeoLua is used to extend the App with Plugins. So the App calls Functions in the Plugin-Scripts, and the Plugin-Script can access certain Properties of some App Objects. And Scripts should be able to call Functions on these Objects too.

But when Updated to 1.3.15, trying to call a Method throws a LuaRuntimeException saysing that this Method was not found:
`2025-10-09 00:53:10.186 [ERR] [ AircraftLua:CallLua              ] Exception catched: 'Neo.IronLua.LuaRuntimeException' - ''Any2GSX.GSX.GsxController:GetService' not found.' - 'System.Object CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Object, System.Object)' -  -- internal --
 at [L] RefuelActive(Closure) line INI.A350.lua:204
`
Reverting back to 1.3.14 fixes the Issue.

<br/>

To give some more Context, that is the Call throwing the Exception

<img width="256" alt="Image" src="https://github.com/user-attachments/assets/96fd1b6d-2cd1-47fa-9029-538b5dae9f56" />

[INI.A350.lua L204](https://github.com/Fragtality/Any2GSX-Plugins/blob/0c6b5cc7d7bc41d896e54bb4dfc6ef278e0e5a5a/iniA350/src/INI.A350.lua#L204)

the gsxController Variable/Object itself works - it is requested in [Line 1](https://github.com/Fragtality/Any2GSX-Plugins/blob/0c6b5cc7d7bc41d896e54bb4dfc6ef278e0e5a5a/iniA350/src/INI.A350.lua#L1) and in Line 25 one of its Properties is read. (The Object passed to the Plugins/Scripts is a "lifetime" Object of the App - so it will not change from the Point the Script initializes to the Point where it throws an Exception)

The GetGsxController Function is a Global injected when the Environment for the Script is created:

<img width="384" alt="Image" src="https://github.com/user-attachments/assets/9fc79e3d-16ad-4358-b18c-11af3f4c1859" />

[AircraftLua.cs L197](https://github.com/Fragtality/Any2GSX/blob/f21f199eaa1217bf6100f8e288c66082b8e80271/Any2GSX/Aircraft/AircraftLua.cs#L197)

**Comment by neolithos** [comment]
Can you add these code, to have a little bit more input.

```Lua
local c = gsxController;
-- print type of c returned
local cgs = c.GetService;
-- print type of cgs returned
cgs(2).StateOverride = 5;
```

Do we have a chance to create a simple example?

Can you rewrite the code to explicit types?
```Lua
local tmp : [type for the result] =  cast(Any2GSX.PluginInterface.Interfaces.IGsxController, gsxConbtroller):GetService(2);
tmp.StateOverride = 5;
```

**Comment by Fragtality** [comment]
> Can you add these code, to have a little bit more input.
> 
> local c = gsxController;
> -- print type of c returned
> local cgs = c.GetService;
> -- print type of cgs returned
> cgs(2).StateOverride = 5;

<img width="539" height="501" alt="Image" src="https://github.com/user-attachments/assets/fb358687-2725-47be-9ea6-c0d557c20a2d" />

still the same:
```
2025-10-18 21:52:09.186 [DBG] [ GsxService:NotifyStateChange     ] Notify State Change for Refuel: Active 
2025-10-18 21:52:09.190 [DBG] [ INI.A350:                        ] userdata 
2025-10-18 21:52:09.192 [DBG] [ INI.A350:                        ] function 
2025-10-18 21:52:09.195 [ERR] [ AircraftLua:CallLua              ] Exception in Lua Function 'RefuelActive': 
2025-10-18 21:52:09.196 [ERR] [ AircraftLua:CallLua              ] Exception catched: 'Neo.IronLua.LuaRuntimeException' - ''Any2GSX.GSX.GsxController:GetService' nicht gefunden.' - 'System.Object CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Object, System.Object)' -  -- Intern --
 bei [L] RefuelActive(Closure) Zeile INI.A350.lua:208
 
2025-10-18 21:52:09.196 [ERR] [ AircraftLua:CallLua              ] INI.A350.lua Line 0 
```

Edit: Reverting back to 1.3.14 with the same Lua Code also prints userdata and function.

<br/><br/>



> Can you rewrite the code to explicit types?
> 
> local tmp : [type for the result] =  cast(Any2GSX.PluginInterface.Interfaces.IGsxController, gsxConbtroller):GetService(2);
> tmp.StateOverride = 5;

If you can give me the exact Syntax? Did not ever cast anything yet - just replacing `type for the result` (with `IGsxService`) has still Syntax Errors in VS Code.


<br/><br/>

> Do we have a chance to create a simple example?

Maybe? ^^
Like a new & general App trying to recreate the Issue or a special Build of Any2GSX recreating the Issue as fast as possible?

**Comment by neolithos** [comment]
I want to see the class, that is resolved in this case. The problem should be somewhere in the member resolver.

```
Log(type(c, true));
```


```
local tmp = cast( ...
```
is for this also enough. But you just need to write the whole name (incl. namespace). Like I did after the `cast`. The syntax error is what I am looking for.

**Comment by Fragtality** [comment]
**First Variant**
<img width="540" height="396" alt="Image" src="https://github.com/user-attachments/assets/06ba546c-e444-4cf7-bf91-e12e2827de77" /><br/>

==>

```
2025-10-20 23:47:11.758 [DBG] [ GsxService:NotifyStateChange     ] Notify State Change for Refuel: Active 
2025-10-20 23:47:11.762 [DBG] [ INI.A350:                        ] Any2GSX.GSX.GsxController 
2025-10-20 23:47:11.764 [DBG] [ INI.A350:                        ] function 
2025-10-20 23:47:11.768 [ERR] [ AircraftLua:CallLua              ] Exception in Lua Function 'RefuelActive': 
2025-10-20 23:47:11.769 [ERR] [ AircraftLua:CallLua              ] Exception catched: 'Neo.IronLua.LuaRuntimeException' - ''Any2GSX.GSX.GsxController:GetService' nicht gefunden.' - 'System.Object CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Object, System.Object)' -  -- Intern --
 bei [L] RefuelActive(Closure) Zeile INI.A350.lua:208
 
2025-10-20 23:47:11.770 [ERR] [ AircraftLua:CallLua              ] INI.A350.lua Line 0 
```

<br/><br/>

**Second Variant**
<img width="1011" height="347" alt="Image" src="https://github.com/user-attachments/assets/0287bf21-3c18-4c4c-8400-94da7d6ad8e8" /><br/>

does not even get that far 😅 (throws Exception when the Plugin/Script is intialized) ==>

```
2025-10-20 23:55:08.221 [ERR] [ AircraftLua:DoInit               ] Exception catched: 'Neo.IronLua.LuaParseException' - ''Any2GSX.PluginInterface.Interfaces.IGsxController:GetService' nicht gefunden.' - 'System.Linq.Expressions.Expression SafeExpression(System.Func`1[System.Linq.Expressions.Expression], Neo.IronLua.Token)' -    at Neo.IronLua.Parser.SafeExpression(Func`1 f, Token tokenStart)
   at Neo.IronLua.Parser.InvokeMemberExpression(Scope scope, Token tStart, Expression instance, String memberName, InvokeResult result, ArgumentsList arguments)
   at Neo.IronLua.Parser.PrefixMemberInfo.GenerateGet(Scope scope, InvokeResult result)
   at Neo.IronLua.Parser.ParseExpressionCast(Scope scope, ILuaLexer code, InvokeResult result, Boolean& doWrap)
   at Neo.IronLua.Parser.ParseExpressionPower(Scope scope, ILuaLexer code, InvokeResult result, Boolean& doWrap)
   at Neo.IronLua.Parser.ParseExpressionUnary(Scope scope, ILuaLexer code, InvokeResult result, Boolean& doWrap)
   at Neo.IronLua.Parser.ParseExpressionMultiply(Scope scope, ILuaLexer code, InvokeResult result, Boolean& doWrap)
   at Neo.IronLua.Parser.ParseExpressionPlus(Scope scope, ILuaLexer code, InvokeResult result, Boolean& doWrap)
   at Neo.IronLua.Parser.ParseExpressionShift(Scope scope, ILuaLexer code, InvokeResult result, Boolean& doWrap)
   at Neo.IronLua.Parser.ParseExpressionCon(Scope scope, ILuaLexer code, InvokeResult result, Boolean& doWrap)
   at Neo.IronLua.Parser.ParseExpressionCmp(Scope scope, ILuaLexer code, InvokeResult result, Boolean& doWrap)
   at Neo.IronLua.Parser.ParseExpressionBitAnd(Scope scope, ILuaLexer code, InvokeResult result, Boolean& doWrap)
   at Neo.IronLua.Parser.ParseExpressionBitXOr(Scope scope, ILuaLexer code, InvokeResult result, Boolean& doWrap)
   at Neo.IronLua.Parser.ParseExpressionBitOr(Scope scope, ILuaLexer code, InvokeResult result, Boolean& doWrap)
   at Neo.IronLua.Parser.ParseExpressionAnd(Scope scope, ILuaLexer code, InvokeResult result, Boolean& doWrap)
   at Neo.IronLua.Parser.ParseExpressionOr(Scope scope, ILuaLexer code, InvokeResult result, Boolean& doWrap)
   at Neo.IronLua.Parser.ParseExpression(Scope scope, ILuaLexer code, InvokeResult result, Boolean& doWrap)
   at Neo.IronLua.Parser.ParseExpression(Scope scope, ILuaLexer code, InvokeResult result, Boolean isDebug)
   at Neo.IronLua.Parser.ParseExpressionList(Scope scope, ILuaLexer code)+MoveNext()
   at Neo.IronLua.Parser.ParseExpressionStatement(Scope scope, ILuaLexer code, Boolean isLocal)
   at Neo.IronLua.Parser.ParseStatement(Scope scope, ILuaLexer code)
   at Neo.IronLua.Parser.ParseBlock(Scope scope, ILuaLexer code)
   at Neo.IronLua.Parser.ParseLamdaDefinition(Scope parent, ILuaLexer code, String name, Boolean hasSelfParameter, Action`1 functionTypeCollected)
   at Neo.IronLua.Parser.ParseFunction(Scope scope, ILuaLexer code, Boolean isLocal)
   at Neo.IronLua.Parser.ParseStatement(Scope scope, ILuaLexer code)
   at Neo.IronLua.Parser.ParseBlock(Scope scope, ILuaLexer code)
   at Neo.IronLua.Parser.ParseChunk(Lua runtime, LuaCompileOptions options, Boolean hasEnvironment, ILuaLexer code, Type typeDelegate, Type returnType, IEnumerable`1 args)
   at Neo.IronLua.Lua.CompileChunkCore(ILuaLexer lex, LuaCompileOptions options, IEnumerable`1 args)
   at Neo.IronLua.Lua.CompileChunk(String code, String name, LuaCompileOptions options, KeyValuePair`2[] args)
   at Any2GSX.Aircraft.AircraftLua.DoInit() 
2025-10-20 23:55:08.221 [ERR] [ AircraftLua:DoInit               ] INI.A350.lua Line 204 
```

<br/><br/>

Third Variant:
`local tmp = cast(Any2GSX.GSX.GsxController, gsxController):GetService(2);`

==>

```
2025-10-20 23:57:11.157 [ERR] [ AircraftLua:DoInit               ] Exception catched: 'Neo.IronLua.LuaParseException' - ''Any2GSX.GSX.GsxController:GetService' nicht gefunden.' - 'System.Linq.Expressions.Expression SafeExpression(System.Func`1[System.Linq.Expressions.Expression], Neo.IronLua.Token)' -    at Neo.IronLua.Parser.SafeExpression(Func`1 f, Token tokenStart)
   at Neo.IronLua.Parser.InvokeMemberExpression(Scope scope, Token tStart, Expression instance, String memberName, InvokeResult result, ArgumentsList arguments)
   at Neo.IronLua.Parser.PrefixMemberInfo.GenerateGet(Scope scope, InvokeResult result)
   at Neo.IronLua.Parser.ParseExpressionCast(Scope scope, ILuaLexer code, InvokeResult result, Boolean& doWrap)
   at Neo.IronLua.Parser.ParseExpressionPower(Scope scope, ILuaLexer code, InvokeResult result, Boolean& doWrap)
   at Neo.IronLua.Parser.ParseExpressionUnary(Scope scope, ILuaLexer code, InvokeResult result, Boolean& doWrap)
   at Neo.IronLua.Parser.ParseExpressionMultiply(Scope scope, ILuaLexer code, InvokeResult result, Boolean& doWrap)
   at Neo.IronLua.Parser.ParseExpressionPlus(Scope scope, ILuaLexer code, InvokeResult result, Boolean& doWrap)
   at Neo.IronLua.Parser.ParseExpressionShift(Scope scope, ILuaLexer code, InvokeResult result, Boolean& doWrap)
   at Neo.IronLua.Parser.ParseExpressionCon(Scope scope, ILuaLexer code, InvokeResult result, Boolean& doWrap)
   at Neo.IronLua.Parser.ParseExpressionCmp(Scope scope, ILuaLexer code, InvokeResult result, Boolean& doWrap)
   at Neo.IronLua.Parser.ParseExpressionBitAnd(Scope scope, ILuaLexer code, InvokeResult result, Boolean& doWrap)
   at Neo.IronLua.Parser.ParseExpressionBitXOr(Scope scope, ILuaLexer code, InvokeResult result, Boolean& doWrap)
   at Neo.IronLua.Parser.ParseExpressionBitOr(Scope scope, ILuaLexer code, InvokeResult result, Boolean& doWrap)
   at Neo.IronLua.Parser.ParseExpressionAnd(Scope scope, ILuaLexer code, InvokeResult result, Boolean& doWrap)
   at Neo.IronLua.Parser.ParseExpressionOr(Scope scope, ILuaLexer code, InvokeResult result, Boolean& doWrap)
   at Neo.IronLua.Parser.ParseExpression(Scope scope, ILuaLexer code, InvokeResult result, Boolean& doWrap)
   at Neo.IronLua.Parser.ParseExpression(Scope scope, ILuaLexer code, InvokeResult result, Boolean isDebug)
   at Neo.IronLua.Parser.ParseExpressionList(Scope scope, ILuaLexer code)+MoveNext()
   at Neo.IronLua.Parser.ParseExpressionStatement(Scope scope, ILuaLexer code, Boolean isLocal)
   at Neo.IronLua.Parser.ParseStatement(Scope scope, ILuaLexer code)
   at Neo.IronLua.Parser.ParseBlock(Scope scope, ILuaLexer code)
   at Neo.IronLua.Parser.ParseLamdaDefinition(Scope parent, ILuaLexer code, String name, Boolean hasSelfParameter, Action`1 functionTypeCollected)
   at Neo.IronLua.Parser.ParseFunction(Scope scope, ILuaLexer code, Boolean isLocal)
   at Neo.IronLua.Parser.ParseStatement(Scope scope, ILuaLexer code)
   at Neo.IronLua.Parser.ParseBlock(Scope scope, ILuaLexer code)
   at Neo.IronLua.Parser.ParseChunk(Lua runtime, LuaCompileOptions options, Boolean hasEnvironment, ILuaLexer code, Type typeDelegate, Type returnType, IEnumerable`1 args)
   at Neo.IronLua.Lua.CompileChunkCore(ILuaLexer lex, LuaCompileOptions options, IEnumerable`1 args)
   at Neo.IronLua.Lua.CompileChunk(String code, String name, LuaCompileOptions options, KeyValuePair`2[] args)
   at Any2GSX.Aircraft.AircraftLua.DoInit() 
2025-10-20 23:57:11.157 [ERR] [ AircraftLua:DoInit               ] INI.A350.lua Line 204 
```

**Comment by Fragtality** [comment]
With `beta.2` still the same :/
(regardless if in its original form or first Variant)

```
2025-10-21 23:59:26.412 [ERR] [ AircraftLua:CallLua              ] Exception catched: 'Neo.IronLua.LuaRuntimeException' - ''Any2GSX.GSX.GsxController:GetService' nicht gefunden.' - 'System.Object CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Object, System.Object)' -  -- Intern --
 bei [L] RefuelActive(Closure) Zeile INI.A350.lua:204
 
2025-10-21 23:59:26.412 [ERR] [ AircraftLua:CallLua              ] INI.A350.lua Line 0 
```

**Comment by Fragtality** [comment]
beta.5 works 🎉 😃 
(Even with the original lua oneliner)
